In [ ]:
pip install numpy


In [1]:
import numpy as np

In [3]:
my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_list = np.arange(0,10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_list = np.arange(0,11,2)
my_list

array([ 0,  2,  4,  6,  8, 10])

In [6]:
my_zeros = np.zeros(7)
my_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
my_ones = np.ones(5)
my_ones

array([1., 1., 1., 1., 1.])

In [8]:
two_d = np.zeros((3,5))
two_d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
lin_arr = np.linspace(0, 1, 5)
lin_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
my_matrx = np.eye(6) 
my_matrx

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
my_rand = np.random.rand(4)
my_rand

array([0.87040582, 0.53918507, 0.73967441, 0.05306871])

In [13]:
my_rand = np.random.rand(5, 4)
my_rand

array([[0.39097984, 0.98156832, 0.90845016, 0.19924757],
       [0.38060984, 0.83011361, 0.90801005, 0.21815794],
       [0.16862638, 0.00904791, 0.10482969, 0.08016985],
       [0.87949247, 0.08986463, 0.32407314, 0.71502431],
       [0.65920004, 0.52261441, 0.89809788, 0.50709108]])

In [14]:
my_randn = np.random.randn(7)
my_randn

array([-1.17591955, -0.1935177 ,  1.85286936, -0.18910611, -1.73499044,
       -0.03827705,  0.42719022])

In [15]:
np.random.randn(3,5)

array([[-0.9123806 ,  0.58250624,  0.85472108, -1.01940946, -0.03948129],
       [ 0.03044562,  0.31653664, -1.92847352, -1.5586019 ,  0.05930339],
       [ 0.57503696, -1.43023975,  0.03222621,  0.59820081, -1.54961417]])

In [61]:
np.random.randint(20) #generates a random integer exclusive of 20

6

In [60]:

np.random.randint(2, 20) #generates a random integer including 2 but excluding 20

8

In [58]:

np.random.randint(2, 20, 7) #generates 7 random integers including 2 but excluding 20

array([15, 18,  3, 15, 13, 19, 16])

In [20]:
arr = np.random.rand(25)
arr

array([0.95502213, 0.68528871, 0.62476132, 0.88887535, 0.79469155,
       0.21065143, 0.63559475, 0.9571306 , 0.17446581, 0.41035692,
       0.41020233, 0.46870038, 0.69239754, 0.15742569, 0.38081931,
       0.38847837, 0.47203651, 0.23006113, 0.70095049, 0.40903346,
       0.24648051, 0.81958455, 0.43395563, 0.01991875, 0.87950442])

In [21]:
arr.reshape(5,5)

array([[0.95502213, 0.68528871, 0.62476132, 0.88887535, 0.79469155],
       [0.21065143, 0.63559475, 0.9571306 , 0.17446581, 0.41035692],
       [0.41020233, 0.46870038, 0.69239754, 0.15742569, 0.38081931],
       [0.38847837, 0.47203651, 0.23006113, 0.70095049, 0.40903346],
       [0.24648051, 0.81958455, 0.43395563, 0.01991875, 0.87950442]])

In [62]:
arr_2 = np.random.randint(0, 20, 10) 

arr_2

array([ 7,  6, 19, 19, 11,  1,  2, 18,  9, 15])

In [64]:
arr_2.max() #This gives the highest value in the array 

19

In [65]:
arr_2.min() #This gives the lowest value in the array

1

In [67]:
arr_2.argmax() #This shows the index of the highest value in the array 


2

In [68]:
arr_2.argmin() #This sh

5

In [69]:
arr.shape

(10,)

In [71]:
my_array = np.arange(0,11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
my_array[5]

5

In [28]:
my_array[2:6] #This returns everything from index 2 to 6(exclusive)

array([2, 3, 4, 5])

In [29]:

my_array[:6] #This returns everything from index 0 to 6(exclusive)

array([0, 1, 2, 3, 4, 5])

In [30]:

my_array[5:] #This returns everything from index 5 to the end of the array.

array([ 5,  6,  7,  8,  9, 10])

In [74]:
two_d_arr = np.array([[10,20,30], [40,50,60], [70,80,90]])
two_d_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [75]:
two_d_arr[1][2] #The value 60 appears is in row index 1, and column index 2

60

In [76]:
two_d_arr[0,1] 

20

In [77]:
two_d_arr[:1, :2]           # This returns [[10, 20]]


array([[10, 20]])

In [34]:
two_d_arr[:2, 1:]           # This returns ([[20, 30], [50, 60]])


array([[20, 30],
       [50, 60]])

In [35]:
two_d_arr[:2, :2]   

array([[10, 20],
       [40, 50]])

In [38]:
new_arr = np.arange(5,15)
new_arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
new_arr > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [78]:
new_arr[(new_arr>6) & (new_arr<10)]

array([7, 8, 9])

In [42]:
my_array[0:3] = 50
my_array

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr * arr  

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
arr - arr  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr / arr  

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr + 50 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [50]:
np.sqrt(arr)     #Returns the square root of each element 
np.exp(arr)     #Returns the exponentials of each element
np.sin(arr)     #Returns the sin of each element
np.cos(arr)     #Returns the cosine of each element
np.log(arr)     #Returns the logarithm of each element
np.sum(arr)     #Returns the sum total of elements in the array

55

In [81]:
mat = np.arange(1,26)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [83]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:

mat.sum()         #Returns the sum of all the values in mat

325

In [85]:

mat.sum(axis=0)   #Returns the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [86]:

mat.sum(axis=1)   #Returns the sum of all the rows in mat

array([ 15,  40,  65,  90, 115])

In [52]:
my_rand

array([[0.39097984, 0.98156832, 0.90845016, 0.19924757],
       [0.38060984, 0.83011361, 0.90801005, 0.21815794],
       [0.16862638, 0.00904791, 0.10482969, 0.08016985],
       [0.87949247, 0.08986463, 0.32407314, 0.71502431],
       [0.65920004, 0.52261441, 0.89809788, 0.50709108]])

In [53]:
my_rand.sum(axis=0)

array([2.47890858, 2.43320888, 3.14346092, 1.71969074])

In [54]:
my_rand.sum(axis=1)

array([2.48024589, 2.33689143, 0.36267383, 2.00845455, 2.58700341])